version: "3"
services:
  teampass:
    image: teampass:2.1.27.36
    restart: always
    volumes:
      - ./volumes/teampass-conf:/usr/share/nginx/html/includes/config
      - ./volumes/teampass-keys:/usr/share/nginx/html/keys
      - ./volumes/teampass-upload:/usr/share/nginx/html/upload
      - ./volumes/teampass-files:/usr/share/nginx/html/files
    ports:
      - "80:80"

  db:
    restart: always
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: TallRaccoon71
      MYSQL_USER: teampass
    volumes:
      - ./volumes/db:/var/lib/mysql