version: "3"
services:
  teampass-web:
    build: .
    image: teampass:2.1.27.36
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: YOUR_HOSTNAME
      VIRTUAL_PORT: 80
      CERT_NAME: YOUR_CERTIFICATE
    ports:
      - 8888:80

  db:
    restart: unless-stopped
    image: yobasystems/alpine-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: teampasspassword
      MYSQL_USER: teampassuser
    volumes:
      - ./teampass-db:/var/lib/mysql

networks:
  frontend:
