version: "3"
services:
  teampass:
    image: teampass:2.1.27.36
    restart: always
    volumes:
      - ./volumes/teampass-conf:/var/www/html/teampass/include/config
    ports:
      - "80:80"

  db:
    restart: always
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: TallRaccoon71
      MYSQL_USER: teampass
    volumes:
      - ./volumes/db:/var/lib/mysql